package persistenceDemo.springBoot.Entity;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;

public class FilmActorPK implements Serializable {

    private short actorId;

    private short filmId;

    public FilmActorPK() {

    }

    public short getActorId() {
        return this.actorId;
    }

    public void setActorId(short actorId) {
        this.actorId = actorId;
    }

    public short getFilmId() {
        return this.filmId;
    }

    public void setFilmId(short filmId) {
        this.filmId = filmId;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + this.actorId;
        hash = 59 * hash + this.filmId;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FilmActorPK other = (FilmActorPK) obj;
        if (this.actorId != other.actorId) {
            return false;
        }
        if (this.filmId != other.filmId) {
            return false;
        }
        return true;
    }

}
