package persistenceDemo.springBoot.Entity;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;

public class FilmCategoryPK implements Serializable {

    private short filmId;

    private short categoryId;

    public FilmCategoryPK() {

    }

    public short getFilmId() {
        return this.filmId;
    }

    public void setFilmId(short filmId) {
        this.filmId = filmId;
    }

    public short getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(short categoryId) {
        this.categoryId = categoryId;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + this.filmId;
        hash = 59 * hash + this.categoryId;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FilmCategoryPK other = (FilmCategoryPK) obj;
        if (this.filmId != other.filmId) {
            return false;
        }
        if (this.categoryId != other.categoryId) {
            return false;
        }
        return true;
    }

}
